export const datas = [
  {
    idCatalogue: 0,
    imageCatalogue: '',
    nomCatalogue: 'maison',
    description: 'une belle maison pour les etudiants',
    location: 'Andrainjato fianarantsoa',
    type: 'Maison a louer',
    motif: "pour avoir de l'argent",
    dateDeCreation: '2021-08-25T07:30:53.756Z',
    nbPiece: 2,
    etage: 0,
    surface: 200,
    prix: 1000,
    monthly: 'mois',
  },
  {
    idCatalogue: 1,
    imageCatalogue: '',
    nomCatalogue: 'Scouteur j90',
    description: 'Une moto en bonne etats',
    location: 'Anosy Antananarivo',
    categorie: 'Moto & Velos',
    motif: "pour avoir de l'argent",
    dateDeCreation: '2021-09-25T07:17:53.756Z',
    nbPiece: null,
    etage: null,
    surface: null,
    prix: 2500,
    monthly: null,
  },
  {
    idCatalogue: 2,
    imageCatalogue: '',
    nomCatalogue: 'maison',
    description: 'Maison pour les famille ou les etudiant.',
    location: 'Ambohitrandriana Ambalavao',
    categorie: "Vente d'imobilier",
    motif: "pour avoir de l'argent",
    dateDeCreation: '2021-09-15T10:17:53.756Z',
    nbPiece: 3,
    etage: 1,
    surface: 200,
    prix: 5000,
    monthly: 'mois',
  },
];
